version: '3.1'
services:
  discovery:
    image: casacambio.com/microservice-docker-discovery:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    networks:
      - local
  bank:
    image: casacambio.com/microservice-docker-bank:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
      - casacambiodomain
    ports:
      - 8082:8082
    networks:
      - local
  customer-service:
    image: casacambio.com/microservice-docker-customer_service:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
      - casacambiodomain
    ports:
      - 8080:8080
    networks:
      - local
  casacambiodomain:
    image: casacambio.com/microservice-docker-casa_cambio_domain:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
    ports:
      - 8081:8081
    networks:
      - local
  bitcoin-service:
    image: casacambio.com/microservice-docker-bitcoin_service:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
      - casacambiodomain
    ports:
      - 8083:8083
    networks:
      - local
  consolidated:
    image: casacambio.com/microservice-docker-consolidated:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
      - casacambiodomain
    ports:
      - 8084:8084
    networks:
      - local
networks:
  local:
    driver: bridge